mod TEST is 
    protecting BITML .
    
    vars S S' : LConfiguration .
    ops A B : -> Participant [ctor] .
    ops x y z : -> Name .
    ops a b : -> Secret .
    op t : -> Nat .
    op p : -> Predicate .  *** 0 ≤ |b | ≤ 1
    op p1 : -> Predicate . *** |a|  =  |b|
    op p2 : -> Predicate . *** |a| =/= |b|

    op Rev : -> AdvContract .
    op Rev1 : -> AdvContract .
    eq Rev = < reveal a . 0 , v(10)> x("a") .
    eq Rev1 = < reveal b . 0 , v(5)> x("b") .
        
    ops D D' D'' : -> AdvContract .
endm

set print color on .

search in TEST : [y] < split(v(1) ~> 0 v(2) ~> 0 v(3) ~> 0), v(6) > y =>* {split(y)}[x("x_0") x("x_1") x("x_2")]< (0).Contract,v(1) > x("x_0") | < (0).Contract,v(2) > x("x_1") | < (0).Contract,v(3) > x("x_2") .
