load bitml.maude

mod TEST is
	protecting BITML_SEM .

ops A B C : -> Participant .
ops X Y Z : -> ContractName .
ops Contr Contr1 Contr2 Contr3 : -> ContractConfiguration .
ops test : -> Contract .


***eq dec = (X := wd A), (Y := wd B) .   
eq dec = (X := (wd A) + rngt X ), (Y := wd B) .   


eq Contr = < tau. wd A  + (wd B)> .
eq Contr1 = < split( (wd A)  (wd B)) > .
eq Contr2 = < *: tau. wd A >  .
eq Contr3 = < rngt X + (wd A)> .

eq test = (wd A) (wd B) .

endm

***rew Contr | unlock  .
***rew Contr1 | unlock  .
***rew Contr2 | unlock  .
rew Contr3 | unlock  .

search Contr3 | unlock =>* G:Configuration .


***search Contr | unlock =>* G:Configuration .
*** red (||  test) .
***red dec . 
***red ref X dec .
***red isDeclared X dec .
***red isDeclared Z dec .

***red isExpanded X  Contr | unlock | X .